=== pfzsteven/KtCompose/routers.dtd
<!ELEMENT routes (group*)>
        <!-- group 标签 -->
        <!ELEMENT group (group*, version*)>
        <!ATTLIST group
                name CDATA #REQUIRED>
        <!-- version 标签 -->
        <!ELEMENT version (route*)>
        <!ATTLIST version
                name (v1 | v2) #REQUIRED>
        <!-- route 标签 -->
        <!ELEMENT route (permission?, class, method, params)>
        <!ATTLIST route
                path CDATA #REQUIRED
                method (get | post | put | delete) #REQUIRED
                authorize (true | false) "false">
        <!-- 可访问某个路由的角色 -->
        <!ELEMENT permission (role*) >
        <!ELEMENT role (#PCDATA)>
        <!ATTLIST role
                name (all|admin|developer|operator|user|guest) #REQUIRED>
        <!-- class 标签 -->
        <!ELEMENT class (#PCDATA)>
        <!-- class > method 标签 -->
        <!ELEMENT method (#PCDATA)>
        <!-- class > method > params 标签 -->
        <!ELEMENT params (param*)>
        <!-- class > params > name 标签 -->
        <!ATTLIST param
                name CDATA #REQUIRED
                type (int|string|float|double|long|short|byte) #REQUIRED
                canBeNull (true | false) "true"
                default CDATA #IMPLIED>
        <!ELEMENT param (enum*)>
        <!ELEMENT enum (#PCDATA)>
        <!ATTLIST enum
                name CDATA #REQUIRED
                value CDATA #REQUIRED>

=== pfzsteven/KtCompose/src/main/resources/routers.xml
<?xml version="1.0" encoding="UTF-8"  ?>
<!DOCTYPE routes SYSTEM "/Users/admin/neo_backend/routers.dtd">
<routes>
    <!-- 后台接口路由示例 -->
    <group name="web apis">
        <group name="user apis">
            <version name="v1">
                <route path="account/login" method="post">
                    <class>com.example.main.LoginHandler</class>
                    <method>loginV1</method>
                    <params>
                        <name type="java.lang.String" canBeNull="false">email</name>
                        <name type="java.lang.String" canBeNull="false">code</name>
                    </params>
                </route>
                <route path="user/info" method="get" authorize="true">
                    <class>com.example.main.UserController</class>
                    <method>getUserInfo</method>
                    <params>
                    </params>
                </route>
            </version>
            <version name="v2">
                <route path="account/login" method="post" authorize="true">
                    <class>com.example.main.LoginHandler</class>
                    <method>loginV2</method>
                    <params>
                        <name type="java.lang.String" canBeNull="false">email</name>
                        <name type="java.lang.String" canBeNull="false">code</name>
                        <name type="java.lang.String" canBeNull="false">mobile</name>
                    </params>
                </route>
            </version>
        </group>
    </group>

    <!-- 客户端接口路由示例 -->
    <group name="app apis">
        <!-- 用户相关api -->
        <group name="user apis">
        </group>
        <!-- 小说api -->
        <group name="">
        </group>
    </group>
</routes>
